# Generated by Django 5.2.6 on 2025-11-07 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgblivros', '0004_rename_data_nasciemento_autor_data_nascimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo_digital',
            field=models.FileField(blank=True, help_text='Opcional: Arquivo PDF ou EPUB para leitura virtual.', null=True, upload_to='ebooks/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='tem_ebook',
            field=models.BooleanField(default=False, help_text='Indica se existe um arquivo digital (eBook) associado a este livro.'),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='sgblivros.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
