# Generated by Django 5.2.6 on 2025-11-09 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgblivros', '0005_livro_arquivo_digital_livro_tem_ebook_emprestimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_livros', models.IntegerField(default=1, verbose_name='Meta de Livros')),
                ('meta_paginas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Meta de Páginas')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data Final Prevista')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('EXPIRADA', 'Expirada')], default='ATIVA', max_length=10, verbose_name='Status')),
                ('livros_completados', models.ManyToManyField(blank=True, related_name='metas_associadas', to='sgblivros.livro', verbose_name='Livros Completados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_leitura', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta de Leitura',
                'verbose_name_plural': 'Metas de Leitura',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
