# Generated by Django 5.2.6 on 2025-11-10 01:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbUsuarios', '0001_initial'),
        ('sgblivros', '0005_livro_arquivo_digital_livro_tem_ebook_emprestimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaleitura',
            options={'verbose_name': 'Livro Lido', 'verbose_name_plural': 'Livros Lidos'},
        ),
        migrations.AddField(
            model_name='metaleitura',
            name='data_conclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaleitura',
            name='livro',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='sgblivros.livro'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='metaleitura',
            unique_together={('usuario', 'livro')},
        ),
        migrations.CreateModel(
            name='LivroLido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_lidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
