# Generated by Django 5.2.6 on 2025-11-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgbUsuarios', '0002_alter_metaleitura_options_metaleitura_data_conclusao_and_more'),
        ('sgblivros', '0005_livro_arquivo_digital_livro_tem_ebook_emprestimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livrolido',
            options={'verbose_name': 'Livro Lido', 'verbose_name_plural': 'Livros Lidos'},
        ),
        migrations.AlterModelOptions(
            name='metaleitura',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Meta de Leitura', 'verbose_name_plural': 'Metas de Leitura'},
        ),
        migrations.AlterUniqueTogether(
            name='metaleitura',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='livrolido',
            name='data_conclusao',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-12', verbose_name='Data de Conclusão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livrolido',
            name='livro',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='sgblivros.livro', verbose_name='Livro Lido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaleitura',
            name='livros_lidos',
            field=models.IntegerField(default=0, verbose_name='Contador de Livros Lidos'),
        ),
        migrations.AlterUniqueTogether(
            name='livrolido',
            unique_together={('usuario', 'livro')},
        ),
        migrations.RemoveField(
            model_name='metaleitura',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='metaleitura',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='metaleitura',
            name='livros_completados',
        ),
    ]
